### ISSUE TITLE
Panopticon Connector update site problem

### ISSUE THREAD

**Issue by nunoleite** [akeeba/panopticon-connector#18]
The update site doesn't report new versions available.

I had to update manually to 1.0.6.

And still it shows only version 1.0.3 available.

![image](https://github.com/user-attachments/assets/22409e53-6abf-4f10-ac0e-8ba78f17f0de)

![image](https://github.com/user-attachments/assets/e2757a04-168f-4850-b345-2f90f2aa4294)

Please update the xml so the Panopticon can be updated automatically.

Thanks

**Comment by nikosdion** [comment]
Done. Will be updated in a few minutes.
