### ISSUE TITLE
problem reinstalling panopticon connector

### ISSUE THREAD

**Issue by pklinke** [akeeba/panopticon-connector#19]
I had a problem with my website and started a restore with akeeba backup. After completion, there was no link to akeeba backup pro and the information could not be updated.  So I uninstalled the connector and tried to reinstall it. However, this failed:

JInstaller: :Install: Die Datei „[ROOT][TMP]/install_6738afe7bbf0b/panopticon-connector-main/component/backend/version.php“ does not exist
Komponente „Installieren“: The files for the administrator directory could not be copied.

What can I do to reinstall the component?

**Comment by nikosdion** [comment]
Assuming we are talking about Joomla! 4 or 5, the [Akeeba Panopticon Connector 1.0.6](https://github.com/akeeba/panopticon-connector/releases/tag/1.0.6), released June 28th, installs fine on Joomla! 4.4, 5.0, 5.1, and 5.2 that I've just tried.

Beyond that, I will note that Joomla's extension installation and update error messages are completely useless. The best I can offer is the generic installation troubleshooting instructions I've written here: https://www.akeeba.com/documentation/akeeba-backup-joomla/installation-updates-upgrades.html#installation-troubleshoot They apply for any Joomla! extension, not just Akeeba Backup.

**Comment by pklinke** [comment]
Don't know what happened. The only thing happened was an update to joomla 5.21 done by panopticon.

Before it was working fine. Now no reinstall of component on destination site, no connection from panopticon installation.
Debugging panopticon test connetion meanwhile throws an error 
Client error: `GET https://URL/api/index.php/v1/panopticon/extensions?page%5Blimit%5D=10000` resulted in a `**403 Forbidden**` response: Wir haben verdächtige Aktivitäten von Ihrer IP-Adresse festgestellt. Ihr Zugriff auf diese Website ist vorübergehend (truncated...)

There is something crumbled.

Both other sites with 5.2.1 and 3.39 are conected.

So I can not use panopticon anymore :-( and must go back to another solution.

**Comment by nikosdion** [comment]
Your installation issue is probably down to a wrong tmp folder. That's why I told you to read the troubleshooting page. One of the first steps there is to check that path to make sure it is correct.

The 403 message you get looks a lot like someone translated the default Admin Tools IP address blocked message to German. Look at Admin Tools' documentation on how to unblock a specific IP address (hint: Web Application Firewall, Unblock an IP) to unblock your Panopticon server's IP address (hint: it's shown when you edit a site, exactly for this reason).

**Comment by pklinke** [comment]
Admin Tools Pro says, that tmp and log-folder are ok. The blocked IP from panopticon-site is now once more unblocked.
Still no success. Firewall on the destination site was temporarily deactivated, no success - here I see a 401 in log-file. I asked the hoster for checking.
Meanwhile 2 other extensions are installed without any problems.

**Comment by pklinke** [comment]
Other extensions are installable, but still not panopticon connector: 

JInstaller: :Install: The file "[ROOT][TMP]/install_6741d931b88a5/panopticon-connector-main/component/backend/version.php" does not exist. Component "Update": The files for the administrator directory could not be copied.

**Comment by nikosdion** [comment]
You are downloading the wrong file. The file you need to download is the `pkg_panopticon-1.0.6.zip` file. It is the item **DIRECTLY ABOVE** the one you clicked on the download page.
