### ISSUE TITLE
Uninstall Package

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon-connector#3]
![image](https://github.com/akeeba/panopticon-connector/assets/1296369/d71ab5ef-f1b3-46ae-a093-b5d763f7af46)

![image](https://github.com/akeeba/panopticon-connector/assets/1296369/2d45f041-4488-4bfa-a2f2-d8f64d94cbe1)

**Comment by nikosdion** [comment]
Thanks. I had noticed that and then promptly forgot about it. It also affected installation. It was a simple typo. Doh.
