### ISSUE TITLE
Tried to connect, but failed J5 and J4

### ISSUE THREAD

**Issue by jamfx** [akeeba/panopticon-connector#5]
Hi Nicholas,
I just wanted to try Panopticon. Setup:
Mydomain . com / panoptiocon -> Panopticon-Installation
Mydomain . com / demofolder1 -> J5-Demosite
Mydomain . com / demofolder2 -> J4-Demosite

**Example 1 - upgraded Demo-Site from J4->J5**
At first I tried at a **J5 site**. The Endpoint was like: mydomain . com/api -> But no connection possible. If I put that URL in the browser it returns a 404
`{"errors":[{"title":"Resource not found","code":404}]}`

**Example 2 On my Demo-J4-Site**
I tried to acces the /api -> But now I got an error "too many redirects"
If I check the Logfiles I got this:
`[Sun Oct 22 18:14:38 2023] [auth_basic:error] [pid 57283:tid 140003745179392] [client 321.321.321.321:51636] AH01614: client used wrong authentication scheme: /mysubfolder/api/index.php/v1/extensions
[Sun Oct 22 18:14:38 2023] [access_compat:error] [pid 57282:tid 140004510398208] [remote 456.456.456.456:47984] AH01797: client denied by server configuration: /usr/www/users/USERNAME/my-folder1/myfolder2/index.php, referer: https://mydemo-domain.tld/myfolder2/index.php?view=site&id=0&returnurl=`

I don't know what happens exactly. As far as I understand:
Example 1: Looks like J5 changed the API-Folder?
Example 2: Maybe my managed server has a special "own" Firewall, I have to ask my Hoster? But all is nearly on the same folder.... :thinking: 
Any suggestions? 
Best regards
Niko

**Comment by nikosdion** [comment]
Try accessing the /api URL of your site from a browser _using Private mode_. Does it ask you for a username and password? If it does, you have password-protected the `/api` folder; this effectively disables the API and you must undo that protection. Did you fall victim to [the unnecessary panic surrounding the Joomla! 4.2.8 security release](https://www.dionysopoulos.me/joomla-428-security-fix-not-end-of-world.html)?

If not, are you using a third party plugin for SEO or redirections? See this issue: https://github.com/akeeba/panopticon/issues/164#issuecomment-1773108178  A third party plugin called Advancedredirect was causing infinite redirects.

**Comment by jamfx** [comment]
Hi Nicholas,
it was the first Problem, you pointed out. 
All Sites (even the Frontend!) is / was protected by .htaccess, because it's my Dev-Playground and I don't want any sniffing arround.
So I removed it temporarily and the connection was established in a second. I didn't realize, that the protection from the Frontend is not asked in Panopticon. :facepalm:  (Why should it...) I gave the credentials for the Backend, but these are not used for frontend-Protection.

My connected J5 Site has an unknown Status. :thinking: 
![j5-demo](https://github.com/akeeba/panopticon-connector/assets/4404552/473d0345-7915-4b04-916f-792ea7b29750)

The J4 Site is listed correctly and shows updates / PHP-Version.
![j4-demo](https://github.com/akeeba/panopticon-connector/assets/4404552/94fbd4df-1339-416a-9367-992ae6c0d694)

Sometimes I get the Message:
`Automated tasks appear to be broken...`
But it's disappearing and coming back. So I guess, that sometimes, the Cron is working and sometimes it's killed by my Hoster. 
This is shown in my log:
`/.tmp/fae49a21da701883ebe482bc8b88e5c5.lck' '/bin/bash' -c '/usr/bin/php82 /usr/www/users/myusername/myfolder1/pano/cli/panopticon.php task:run --loop >/dev/null 2>&1')`

Is everything fine? :thinking: 
Best regards
Niko

**Comment by nikosdion** [comment]
Remember that when you add a new site it _might_ take a few minutes for the information to fill in. This depends on whether Panopticon can fetch the information when you save the site.

If you click on the reload button next to the unknown status and nothing happens, you have some kind of problem on your site's end (possibly a timeout, which can happen if you have _a lot_ of extensions).

Regarding the message about automated tasks, it only appears if Panopticon has not detected the heartbeat signal from the CLI CRON job for more than 55 seconds. This check takes place approximately every 30 seconds. It is possible that your server experiences high load and delays the execution of CRON jobs by a couple of seconds and/or kill the CRON script. As you can see, the timing _may_ lead to the heartbeat failing if the host delayed executing the CRON job long enough to get the last heartbeat signal out of the 55 second detection window.
